version: '3.4'

networks: 
  localdev:    

services:
  webapiwithdi:
    image: webapiwithdi
    build:
      context: .
      dockerfile: WebApiWithDI/Dockerfile
    networks:
      - localdev
    restart: always
  db-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db-server
    environment:
      SA_PASSWORD: Altran2019!
      ACCEPT_EULA: Y    
    ports:
      - "1433:1433"
    networks: 
      - localdev