version: '3.5'

networks: 
  localdev:
    name: localdev

services:
  webapiwithdi:
    image: webapiwithdi
    build:
      context: .
      dockerfile: WebApiWithDI/Dockerfile
    networks:
      - localdev
    restart: always
    ports:
      - "62528:80"
    depends_on: 
      - db-server
  db-server:
    image: sqlserver
    build:
      context: .
      dockerfile: WebApiWithDI/sqlserver.Dockerfile
    volumes:
      - ./data:/var/opt/mssql/data 
    ports:
      - "1433:1433"
    networks: 
      - localdev