// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiWithDI;

namespace WebApiWithDI.Migrations
{
    [DbContext(typeof(TodoContextSqlServer))]
    [Migration("20200205190405_WebApiWithDI.TodoContextSqlServer")]
    partial class WebApiWithDITodoContextSqlServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiWithDI.Models.TodoItemSqlServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TodoItemSqlServer");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Lluis",
                            IsComplete = true
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Josep",
                            IsComplete = true
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Enric",
                            IsComplete = true
                        },
                        new
                        {
                            Id = 4L,
                            FirstName = "Ricard",
                            IsComplete = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
